In [21]:
import pandas as pd

In [22]:
newdata = pd.read_csv('data/data.csv')
newdata = newdata[0:10000]
newdata['comment_body'] = newdata['comment_body'].str.replace('([“”¨«»®´·º½¾¿¡§£₤‘’\n\r>])', '')
#newdata['comment_body'] = [data.replace(';', ':') for data in newdata['comment_body']]
newdata = newdata.dropna()
newdata['length'] = [len(x) for x in newdata['comment_body']]
newdata = newdata[newdata.length <= 512]
ids = [i for i in range(len(newdata))]
ups = list(newdata["upvotes"])

In [23]:
val = [0]*len(newdata)
for i in range(len(newdata)):
    x = ups[i]
    if x < 0:
        val[i] = 0
    elif (x>=1 and x<=3):
        val[i] = 1
    elif (x>=4 and x<=9):
        val[i] = 2
    elif (x>=10):
        val[i] = 3
newdata["label"] = val
cols = ["label", "text"]
newdata["text"] = newdata["comment_body"]
newdata = newdata[cols]
newdata
#newdata.to_csv("data/all-labeled.csv", index=False)

      label                                               text
2         3  Peter Quill and Gamora will NOT end up togethe...
4         3  The opening scene of Ant-Man 3 will be Luis as...
7         2  Latveria (but not Dr. Doom yet) will be introd...
8         1  Gamma radiation will create mutantsWe know tha...
9         1  Kathryn Hahn is almost certainly Agatha Harkne...
...     ...                                                ...
9995      1  They don't want people binging the entire seri...
9996      1  ? Bingeing makes way more sense for movie cros...
9997      0  Why would you want an episode to come out a we...
9998      1  Or you'd want to flesh it out so people can di...
9999      1  I mean as long as its finished a while before ...

[9561 rows x 2 columns]

In [24]:
newdata = newdata.sample(frac=1).reset_index(drop=True)
splitby = int(0.8*len(newdata))
train_data = newdata[:splitby]
test_data = newdata[splitby:]
train_data = train_data.dropna()
test_data = test_data.dropna()
train_data

      label                                               text
0         2  This. Hes totally wrong. Its not like anyone j...
1         1  It could have worked well in Endgame though.I ...
2         0                           Not how timetravel works
3         3                              He means Happy Hogan.
4         2                  Hes balancing on the flying horse
...     ...                                                ...
7643      1  I'm really glad they got to live happily ever ...
7644      0  Thats crazy to me. I dont see ANY of these mov...
7645      1              He would become a God if he does that
7646      3  No I mean we cant know what Cap does or does n...
7647      3  I guess you could say Evans is an All Cap kind...

[7648 rows x 2 columns]

In [25]:
train_data.to_csv("train.csv", index=False, columns=["label", "text"])
test_data.to_csv("test.csv", index=False, columns=["label", "text"])